###------------REGISTER-------------------------------------
POST  http://127.0.0.10:3010/auth/users/register
Content-Type: application/json

{
    "name": "Gerson",
    "last_name": "Hernández Olave",
    "email": "gerson@example.com",
    "username": "gersonhdz",
    "password": "gerson123",
    "dni": "1096248657"       
}

###
POST  http://127.0.0.10:3010/auth/users/register
Content-Type: application/json

{
    "name": "Gerson",
    "last_name": "Hernández Olave",
    "email": "gersonhdz@example.com",
    "username": "gersonhdz8",
    "password": "gerson1234",
    "dni": "10962486579"       
}

###
POST  http://127.0.0.10:3010/auth/users/register
Content-Type: application/json

{
    "name": "Gerson",
    "last_name": "Hernández Olave",
    "email": "gersonhdz00@example.com",
    "username": "gersonhdz00",
    "password": "gerson12345",
    "dni": "10962486578"       
}
###------------LOGIN-----------------------------------------
#client
POST  http://127.0.0.10:3010/auth/users/login
Content-Type: application/json

{
    "username": "gersonhdz",
    "password": "gerson123"
}

###admin
POST  http://127.0.0.10:3010/auth/users/login
Content-Type: application/json

{
    "username": "gersonhdz8",
    "password": "gerson1234"
}


###superadmin
POST  http://127.0.0.10:3010/auth/users/login
Content-Type: application/json

{
    "username": "gersonhdz00",
    "password": "gerson12345"
}

###-----------------SUPERADMIN-------------------------
### Buscar todos los usuarios clientes
GET http://127.0.0.10:3010/aplication/admin/getAllUserClients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

### OBTENER TODOS LOS USUARIOS
GET http://127.0.0.10:3010/aplication/superadmin/getAllUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

### CAMBIAR ROL DE USUARIO
PATCH  http://127.0.0.10:3010/aplication/superadmin/rolUser/7/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo



###-------------------- CLIENTES---------------------

###Todos los productos
GET http://127.0.0.10:3010/aplication/client/getAllInventories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE4ZWQ5NTQzNGQwOTRjZDE5ZmIzN2MiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJnZXJzb25oZHoiLCJwYXNzd29yZCI6IiQyYiQxMCR2RU9SY1JlTjVXOU9qRkVVdGNENFBPWkVrLzNHTWNSZ09qUVFFVFhoQW5QdGRKdFZQejZLLiIsImRuaSI6IjEwOTYyNDg2NTciLCJpZCI6Nywicm9sZSI6ImNsaWVudCIsImlhdCI6MTY5NjIwMDkzNSwiZXhwIjoxNjk2MjA0NTM1fQ.wFAYADpEysm5xVi9i77LMWxAEiSPPLBxyAZRaRFjimE

###Inventario por categoria
GET http://127.0.0.10:3010/aplication/client/getInventoryCategory/Misterio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE4ZWQ5NTQzNGQwOTRjZDE5ZmIzN2MiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJnZXJzb25oZHoiLCJwYXNzd29yZCI6IiQyYiQxMCR2RU9SY1JlTjVXOU9qRkVVdGNENFBPWkVrLzNHTWNSZ09qUVFFVFhoQW5QdGRKdFZQejZLLiIsImRuaSI6IjEwOTYyNDg2NTciLCJpZCI6Nywicm9sZSI6ImNsaWVudCIsImlhdCI6MTY5NjIwMDg0MCwiZXhwIjoxNjk2MjA0NDQwfQ.TbE6QBnl_tEDhQDzeCuNdpGkQylphQH3ShJvk9MSnqU

###Detalles de las reservas por dni de usuario
GET http://127.0.0.10:3010/aplication/client/reserveDetails/456789123C
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE4ZWQ5NTQzNGQwOTRjZDE5ZmIzN2MiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJnZXJzb25oZHoiLCJwYXNzd29yZCI6IiQyYiQxMCR2RU9SY1JlTjVXOU9qRkVVdGNENFBPWkVrLzNHTWNSZ09qUVFFVFhoQW5QdGRKdFZQejZLLiIsImRuaSI6IjEwOTYyNDg2NTciLCJpZCI6Nywicm9sZSI6ImNsaWVudCIsImlhdCI6MTY5NjIwMDg0MCwiZXhwIjoxNjk2MjA0NDQwfQ.TbE6QBnl_tEDhQDzeCuNdpGkQylphQH3ShJvk9MSnqU

###Crear reserva
POST  http://127.0.0.10:3010/aplication/client/newReserve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE4ZWQ5NTQzNGQwOTRjZDE5ZmIzN2MiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJnZXJzb25oZHoiLCJwYXNzd29yZCI6IiQyYiQxMCR2RU9SY1JlTjVXOU9qRkVVdGNENFBPWkVrLzNHTWNSZ09qUVFFVFhoQW5QdGRKdFZQejZLLiIsImRuaSI6IjEwOTYyNDg2NTciLCJpZCI6Nywicm9sZSI6ImNsaWVudCIsImlhdCI6MTY5NjIwMDg0MCwiZXhwIjoxNjk2MjA0NDQwfQ.TbE6QBnl_tEDhQDzeCuNdpGkQylphQH3ShJvk9MSnqU

{
    "products": [
        { "serialGroup": "A1", "cantidad_reserva": 1 },
        { "serialGroup": "B2", "cantidad_reserva": 1 }
    ],
    "dni": "456789123C",
    "customerName": "Gerson",
    "date": "2023-09-26T14:30:00Z"    
}

###Cancelar una reserva
PATCH   http://127.0.0.10:3010/aplication/client/canceledReserve/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTE4ZWQ5NTQzNGQwOTRjZDE5ZmIzN2MiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJnZXJzb25oZHoiLCJwYXNzd29yZCI6IiQyYiQxMCR2RU9SY1JlTjVXOU9qRkVVdGNENFBPWkVrLzNHTWNSZ09qUVFFVFhoQW5QdGRKdFZQejZLLiIsImRuaSI6IjEwOTYyNDg2NTciLCJpZCI6Nywicm9sZSI6ImNsaWVudCIsImlhdCI6MTY5NjIwMDg0MCwiZXhwIjoxNjk2MjA0NDQwfQ.TbE6QBnl_tEDhQDzeCuNdpGkQylphQH3ShJvk9MSnqU

###--------ADMIN-------------------------------

##Buscar todos los productos
GET http://127.0.0.10:3010/aplication/admin/getAllProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

###Buscar todas las reservas
GET http://127.0.0.10:3010/aplication/admin/getAllReservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo


### Buscar todos los usuarios clientes
GET http://127.0.0.10:3010/aplication/admin/getAllUserClients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo


### Crear producto
POST http://127.0.0.10:3010/aplication/admin/newProduct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

{
    "serial": "A1"
}

### Buscar todos las reservas
GET http://127.0.0.10:3010/aplication/admin/getAllReservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

### Buscar inventario por serial
GET http://127.0.0.10:3010/aplication/admin/getInventorySerial/E5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

### Actualizar producto por id
PATCH  http://127.0.0.10:3010/aplication/admin/updateProduct/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

{
    "serial":"A5",
    "status":"En préstamo"
}

### Eliminar producto por id
DELETE   http://127.0.0.10:3010/aplication/admin/deleteProduct/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

### Crear inventario 
POST   http://127.0.0.10:3010/aplication/admin/newInventory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

{
    
    "serialGroup": "YYY25",
    "name": "Los Dinosaurios",
    "description": "Descubre criaturas prehistóricas en este libro fascinante.",
    "image_url": "https://img.freepik.com/fotos-premium/portada-libro-kdp-historia-aventuras-ninos-dinosaurios-generada-ia_996128-292.jpg?w=360",
    "category": ["Aventura", "Paleontología"],
    "quantity": 5,
    "inStock": 5,
    "inLoan": 0,
    "price": 1899,
    "location": "Estante ZY-5"
}

### Actualizar inventario 
PATCH  http://127.0.0.10:3010/aplication/admin/updateInventory/YYY25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

{
    
    "name": "Los Campers de campuslandia",
    "description": "Descubre criaturas prehistóricas como kevin.",
    "image_url": "https://img.freepik.com/fotos-premium/portada-libro-kdp-historia-aventuras-ninos-dinosaurios-generada-ia_996128-292.jpg?w=360",
    "category": ["Aventura", "Programacion"],    
    "location": "Estante Zona franca"
}

### Actualizar estado de reserva  
PATCH  http://127.0.0.10:3010/aplication/admin/statusReserve/1/Aprobada
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo


### Crear Prestamo  
POST   http://127.0.0.10:3010/aplication/admin/createLoan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

{
    
    "products": [{ "id_product": 1 }],
    "dni": "987654321B",
    "customerName": "Juan Pérez",
    "date": "2023-09-25T10:00:00Z",
    "returnDate": "2023-10-02T10:00:00Z"    
}

### Buscar todos los prestamos
GET http://127.0.0.10:3010/aplication/admin/getAllLoans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

### Actualizar Prestamo por id 
PATCH  http://127.0.0.10:3010/aplication/admin/statusLoan/4/Devuelto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTFhMzI2ZmEwNmU3MTUwYjVlNTc5MjMiLCJuYW1lIjoiR2Vyc29uIiwibGFzdF9uYW1lIjoiSGVybsOhbmRleiBPbGF2ZSIsImVtYWlsIjoiZ2Vyc29uaGR6MDBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImdlcnNvbmhkejAwIiwicGFzc3dvcmQiOiIkMmIkMTAkQ3BCNm9VNm9VYUJOTFZJc0FOTmE1T1FsU1BkVkFMZS5MTjVUY3pTNGh6U2l0a25LNFBIUW0iLCJkbmkiOiIxMDk2MjQ4NjU3OCIsImlkIjo4LCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY5NjIxNTc3OSwiZXhwIjoxNjk2MjE5Mzc5fQ.IF6qSd5eu6lDVIYq7dF6b4cB5KfkBYtBwnWXAofKYoo

